# Generated by Django 5.1 on 2025-02-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_id",
        ),
    ]
