# Generated by Django 5.1 on 2025-02-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=50)),
                ("project_name", models.CharField(max_length=50)),
                ("project_description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testing",
            fields=[
                (
                    "test_id",
                    models.AutoField(
                        db_index=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "testing_type",
                    models.CharField(
                        choices=[
                            ("LLM", "LLM"),
                            ("GitLeaks", "GitLeaks"),
                            ("Nuclie", "Nuclie"),
                            ("CVEscan", "CVEscan"),
                        ],
                        default="LLM",
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField()),
                ("test_result", models.URLField()),
                ("repo_folder_name", models.TextField(blank=True, default="")),
                (
                    "testing_status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Cloning", "Cloning"),
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Waiting",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
