# Generated by Django 5.1 on 2025-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_project_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="testing",
            name="test_count",
            field=models.IntegerField(default=0),
        ),
    ]
